name = "projectx"
compatibility_date = "2025-05-03"

# Build configuration
[build]
command = "npm run build"

# Main configuration
main = "workers-site/index.js"

# Assets configuration
[site]
bucket = "./dist"
entry-point = "workers-site"

# Account configuration
account_id = "217f6f87437d3b5067efae8c720b84bc"
zone_id = "4a714e5e166064e604d4d7a6d6a86db5"
